### ISSUE TITLE
IndexError: too many indices for array

### ISSUE THREAD

**Issue by h510166404** [guoruoqian/FPN_Pytorch#6]
[session 1][epoch  1][iter 1500/6468] loss: 0.5808, lr: 1.00e-03
			fg/bg=(7/121), time cost: 23.705823
			rpn_cls: 0.0890, rpn_box: 0.0042, rcnn_cls: 0.2387, rcnn_box 0.1058
Traceback (most recent call last):
  File "trainval_net.py", line 355, in <module>
    data = data_iter.next()
  File "/home/hyc/anaconda2/lib/python2.7/site-packages/torch/utils/data/dataloader.py", line 281, in __next__
    return self._process_next_batch(batch)
  File "/home/hyc/anaconda2/lib/python2.7/site-packages/torch/utils/data/dataloader.py", line 301, in _process_next_batch
    raise batch.exc_type(batch.exc_msg)
IndexError: Traceback (most recent call last):
  File "/home/hyc/anaconda2/lib/python2.7/site-packages/torch/utils/data/dataloader.py", line 55, in _worker_loop
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/home/hyc/FPN_Pytorch-master/lib/roi_data_layer/roibatchLoader.py", line 67, in __getitem__
    blobs = get_minibatch(minibatch_db, self._num_classes)
  File "/home/hyc/FPN_Pytorch-master/lib/roi_data_layer/minibatch.py", line 30, in get_minibatch
    im_blob, im_scales = _get_image_blob(roidb, random_scale_inds)
  File "/home/hyc/FPN_Pytorch-master/lib/roi_data_layer/minibatch.py", line 73, in _get_image_blob
    im = im[:,:,::-1]

**Comment by h510166404** [comment]
When I train my own dataset,i meet this problem
